<?php

declare(strict_types=1);

use App\Enums\StockMovementTypeEnum;
use App\Models\StockMovementSequence;
use App\Services\StockMovementService;
use Database\Seeders\ItemSeeder;
use Database\Seeders\StockMovementSeeder;
use Database\Seeders\StoreSeeder;
use Database\Seeders\UserSeeder;

\test('StockMovementSeeder lazily creates one sequence row per (user, type, year) combination', function (): void {
    (new UserSeeder())->run();
    (new StoreSeeder())->run();
    (new ItemSeeder())->run();

    \expect(StockMovementSequence::query()->count())->toBe(0);

    (new StockMovementSeeder())->run();

    $user = App\Models\User::query()->first();
    \assert($user instanceof App\Models\User);

    $year = (int) Illuminate\Support\Carbon::now()->format('Y');
    $rows = StockMovementSequence::query()
        ->where('user_id', $user->getKey())
        ->where('year', $year)
        ->get();

    $seenTypes = $rows->pluck('type')->all();
    \expect($seenTypes)->toContain(StockMovementTypeEnum::INCOMING->value);
    \expect($seenTypes)->toContain(StockMovementTypeEnum::OUTGOING->value);
    \expect($seenTypes)->toContain(StockMovementTypeEnum::ADJUSTMENT->value);

    // Each sequence row is a counter that exceeds the number of
    // movements of its type generated by the seeder.
    $movementCount = App\Models\StockMovement::query()->where('user_id', $user->getKey())->count();
    \expect($rows->sum('last_number'))->toBeGreaterThanOrEqual($movementCount);

    // Sanity: the service and the seeder agree on how to call next().
    $next = \app(StockMovementService::class);
    \expect($next)->toBeInstanceOf(StockMovementService::class);
});
