<?php

declare(strict_types=1);

$supported = [
    'attendance.index' => ['tool' => 'read_attendance', 'dataset' => 'sessions'],
    'attendance.report' => ['tool' => 'read_attendance', 'dataset' => 'monthly_report'],
    'attendance.print' => ['tool' => 'read_attendance', 'dataset' => 'monthly_report'],
    'checklists.index' => ['tool' => 'read_checklists', 'dataset' => 'days'],
    'gift-vouchers.index' => ['tool' => 'read_gift_vouchers', 'dataset' => 'vouchers'],
    'income-expenses.index' => ['tool' => 'read_financial_reports', 'dataset' => 'reports'],
    'income-expenses.recurring-expenses.index' => ['tool' => 'read_recurring_expenses', 'dataset' => 'expenses'],
    'inventory-counts.index' => ['tool' => 'read_inventory_counts', 'dataset' => 'sessions'],
    'inventory-counts.history' => ['tool' => 'read_inventory_counts', 'dataset' => 'sessions'],
    'inventory-counts.show' => ['tool' => 'read_inventory_counts', 'dataset' => 'sessions'],
    'items.index' => ['tool' => 'read_items', 'dataset' => 'catalog'],
    'items.search' => ['tool' => 'read_items', 'dataset' => 'catalog'],
    'items.show' => ['tool' => 'read_items', 'dataset' => 'catalog'],
    'items.edit' => ['tool' => 'read_items', 'dataset' => 'catalog'],
    'payroll.index' => ['tool' => 'read_payroll', 'dataset' => 'reports'],
    'payroll.show' => ['tool' => 'read_payroll', 'dataset' => 'payslips'],
    'payroll.print' => ['tool' => 'read_payroll', 'dataset' => 'reports'],
    'recipe-categories.index' => ['tool' => 'read_recipes', 'dataset' => 'categories'],
    'recipes.index' => ['tool' => 'read_recipes', 'dataset' => 'recipes'],
    'recipes.show' => ['tool' => 'read_recipes', 'dataset' => 'recipes'],
    'recipes.edit' => ['tool' => 'read_recipes', 'dataset' => 'recipes'],
    'recipe-tests.show' => ['tool' => 'read_recipe_tests', 'dataset' => 'attempts'],
    'recipe-test-sessions.show' => ['tool' => 'read_recipe_tests', 'dataset' => 'sessions'],
    'recipe-test-results.index' => ['tool' => 'read_recipe_tests', 'dataset' => 'sessions'],
    'recipe-test-results.show' => ['tool' => 'read_recipe_tests', 'dataset' => 'attempts'],
    'settings.show' => ['tool' => 'read_settings', 'dataset' => 'profile'],
    'settings.slack-digests.index' => ['tool' => 'read_settings', 'dataset' => 'digests'],
    'settings.slack-digests.show' => ['tool' => 'read_settings', 'dataset' => 'digests'],
    'shifts.index' => ['tool' => 'read_shifts', 'dataset' => 'shifts'],
    'statements.index' => ['tool' => 'read_statements', 'dataset' => 'reports'],
    'statements.history' => ['tool' => 'read_statements', 'dataset' => 'reports'],
    'statements.versions.show' => ['tool' => 'read_statements', 'dataset' => 'reports'],
    'stock-movements.index' => ['tool' => 'read_stock_movements', 'dataset' => 'movements'],
    'stock-movements.show' => ['tool' => 'read_stock_movements', 'dataset' => 'movements'],
    'stock-movements.create' => ['tool' => 'read_items', 'dataset' => 'store_stock'],
    'stores.index' => ['tool' => 'read_stores', 'dataset' => 'stores'],
    'stores.show' => ['tool' => 'read_stores', 'dataset' => 'stores'],
    'stores.edit' => ['tool' => 'read_stores', 'dataset' => 'stores'],
    'users.index' => ['tool' => 'read_users', 'dataset' => 'users'],
    'users.edit' => ['tool' => 'read_users', 'dataset' => 'users'],
    'workers.index' => ['tool' => 'read_workers', 'dataset' => 'workers'],
    'workers.edit' => ['tool' => 'read_workers', 'dataset' => 'workers'],
];

return [
    'supported' => $supported,
    'assistant_only' => [
        'read_settings:integrations' => 'Safe Slack configuration status shares the settings page with profile data.',
        'read_settings:digests' => 'Digest summaries are available without exposing Slack payload secrets.',
        'read_shift_requests:requests' => 'Shift requests are embedded in the shifts calendar page.',
        'read_shift_requests:month_locks' => 'Month locks are embedded in the shifts calendar page.',
        'read_shift_share_links:share_links' => 'Safe share-link lifecycle metadata is embedded in the shifts page; bearer tokens are excluded.',
        'read_checklists:items' => 'Checklist item details are embedded in checklist days.',
        'read_noticeboard:cards' => 'Noticeboard cards are embedded in the dashboard composite.',
        'read_items:store_stock' => 'Per-store stock powers inventory and stock-movement forms in addition to the catalog.',
        'read_statements:days' => 'Statement day rows are embedded in statement reports.',
        'read_recurring_expenses:versions' => 'Version history is assistant-readable detail for the recurring-expense page.',
        'read_gift_vouchers:batches' => 'Safe batch metadata is available while printable codes remain excluded.',
        'read_financial_reports:rows' => 'Financial rows are embedded in the monthly financial report.',
    ],
    'excluded' => [
        'assistant.index' => 'Assistant control-plane page, not business data.',
        'assistant.conversations.show' => 'Assistant transcript control-plane data.',
        'assistant.turns.stream' => 'Durable event transport.',
        'bank-statements.index' => 'Sensitive bank imports are deliberately excluded from assistant context.',
        'bank-statements.show' => 'Sensitive bank transactions are deliberately excluded from assistant context.',
        'bank-statements.original' => 'Private binary bank documents are deliberately excluded from assistant context.',
        'dashboard' => 'Composite presentation assembled from data already covered by attendance, shifts, checklists, noticeboard, statements, and inventory readers.',
        'noticeboard-cards.image' => 'Binary image content is deliberately excluded from model context.',
        'gift-voucher-batches.print' => 'Printable voucher codes and binary output are deliberately excluded.',
        'gift-voucher-batches.create' => 'Voucher issuance form; batch creation uses the existing mutation workflow.',
        'gift-voucher-settings.edit' => 'Voucher branding form, including a private logo preview; no assistant branding reader is exposed.',
        'gift-vouchers.redeem-page' => 'Interactive voucher lookup with a session-bound redemption ticket; excluded from assistant reads.',
        'gift-vouchers.print' => 'Printable voucher codes and binary output are deliberately excluded.',
        'items.create' => 'Form defaults only; catalog data is covered by read_items.',
        'stores.create' => 'Form defaults only; store data is covered by read_stores.',
        'users.create' => 'Form defaults only; user assignments are covered by read_users.',
        'workers.create' => 'Form defaults only; worker data is covered by read_workers.',
        'recipes.create' => 'Form defaults only; recipes and categories are covered by read_recipes.',
        'reports.index' => 'Composite UI assembled from statements, stock, attendance, and finance readers.',
        'reports.statistics' => 'Composite visualization assembled from statements, stock, attendance, and finance readers.',
        'verify-email.show' => 'Email-verification lifecycle is excluded from chat.',
    ],
];
